name: trade_the_fed
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - jupyter
  - python=3.8.8
  - pip=21.0.1
  - pytorch=2.0.1
  - matplotlib
  - seaborn
  - pandas=1.2.4
  - numpy
  - scikit-learn
  - joblib
  - tqdm
  - ipython
  - pyarrow
  - statsmodels
  - pydantic==2.0.2
  - pip:
    - click
    - omegaconf==2.0.5
    - python-dotenv
    - transformers==4.30.2
    - xgboost
    - typer[all]
    - mlflow==1.28.0
    - flask==2.1.3
    - pytube
    - openai-whisper
    - mplfinance
    - alpaca-trade-api
    - nltk
    - ffmpeg-python
    - pypdf
    - alpaca-py
